```{r}
library(dplyr)
library(readr)
library(ggplot2)
```

```{r Read in dataset}
getwd()

Pec_1 <- read.csv("Data/Raw_Data/PEC-1 (1).csv")
head(Pec_1)
```


```{r clean data set and summarize data}


#grouped and calculated to total kWh for low consumption areas and High consumption areas.
summary_data <-Pec_1 %>%
  group_by(high_adopt, year) %>%
  summarise(total_kwh=sum(kwh_total))


str(summary_data)
summary_data$total_kwh <- as.numeric(summary_data$total_kwh)


```

```{r}
is.na(Pec_1)

Pec_final1<- Pec_1 %>%
    group_by(canton) %>%
    mutate(high_adopt_imputed = 
   replace_na(high_adopt, median(high_adopt, na.rm = T))) %>%
    mutate(hosp_rate_imputed = 
   replace_na(total_hosp, median(total_hosp, na.rm = T))) %>%
   ungroup()

Pec_final_test <- Pec_final1%>% 
  group_by(high_adopt_imputed, year) %>% 
  summarise(total_kwh=sum(kwh_total))

Pec_final_test_2 <- Pec_final1%>% 
  group_by(canton, year) %>% 
  summarise(total_kwh=sum(kwh_total))

Pec_final_test_2 <- Pec_final1%>% 
  group_by(canton, high_adopt_imputed, year) %>% 
  summarise(total_kwh=sum(kwh_total))
```

