D


>DONT LOOk AT THIS CODE. IT IS OLD. USE "test" INSTEAD. 
  -VINNY


```{r}


library(dplyr)
library(readr)
library(ggplot2)

```

```{r Read in dataset}
getwd()

Pec_1 <- read.csv("Data/Raw_Data/PEC-1 (1).csv")
head(Pec_1)

```

```{r Wrangled Data}
is.na(Pec_1)

Pec_final1<- Pec_1 %>%
    group_by(canton) %>%
    mutate(high_adopt_imputed = 
   replace_na(high_adopt, median(high_adopt, na.rm = T))) %>%
    mutate(hosp_rate_imputed = 
   replace_na(total_hosp, median(total_hosp, na.rm = T))) %>%
   ungroup()

Pec_final_test_2 <- Pec_final1%>% 
  group_by(canton, high_adopt_imputed, year) %>% 
  summarise(total_kwh=sum(kwh_total))

Pec_final_hr_summ <- Pec_final_hr %>%
  select(total_hr) %>% 
  summarize(
                    length.hr=length(total_hr)-sum(is.na(total_hr)),
                    mean.total_hr=mean(total_hr),
                    median.total_hr=median(total_hr),
                    sd.total_hr=sd(total_hr),
                    skew.total_hr=skewness(total_hr),
                    )

Pec_final_hr_summ

```

```{r Summary Statisics}
dfs
```


```{r paired test from jackson}
t.test(Pec_final_test_2$high_adopt_imputed, Pec_final_test_2$total)
```


>a.	Energy Consumption Levels in high adoption areas vs Energy Consumption Levels in low adoption areas (all years). 

```{r}

```


```{r clean data set and summarize data}

shapiro.test(Pec_final_test_2$total_kwh)

```


```{r Sumarize Energy Consumption}

#created bar chart to visulaize
ggplot(summary_data, aes(x = factor(high_adopt), y = total_kwh, fill = factor(high_adopt))) +
  geom_bar(stat = "identity") + #"identify" is used for data when already summed
  labs(x = "Adoption Level",  y = "Total Energy Consumption (kWh)",  title = "Energy Consumed in High vs Low adoption areas") +
      scale_y_continuous(labels = scales::comma)+#stops scientific notation from showing on chart
  scale_fill_manual(values= c("0" ="blue", "1" ="green"),
                    labels = c("Low Adoption","High Adoption"))
```
